### ISSUE TITLE
Boolean media queries not working

### ISSUE THREAD

**Issue by mahmoud** [fedorovvvv/svelte-media-queries#10]
Hey Nikita! 

Nice work on this library. I noticed an issue with dynamic media queries. Compound queries return `false`, even when the individual queries return `true`. 

Take a look at this screenshot from the REPL and I think you'll understand the issue:

![Screenshot from 2022-11-30 15-57-07](https://user-images.githubusercontent.com/130193/204933559-2cdd92ab-6ce2-4a93-89e9-4abadcd34d46.png)

I expected `[true, true, true]` in that last line. 

Thanks again!

**Comment by fedorovvvv** [comment]
Hey!
Really, I made a mistake with a space in ```value.replace(/\s/g,")```
Thank you for your attention✨
