### ISSUE TITLE
[TypeScript] Type error on destructured matches property when using array of queries

### ISSUE THREAD

**Issue by thomasdom** [fedorovvvv/svelte-media-queries#12]
### Description

When using `<MediaQuery>` component with an array of queries in `query` prop, Svelte indicates a cryptic TypeScript error on `let:matches` destructured property.

### How to reproduce

```svelte
<MediaQuery
        query={['(min-width: 768px) and (max-width: 1023px)', '(min-width: 1024px)']}
	let:matches
>
        <!-- Type error appears here on IDE -->
        {@const [tablet, desktop] = matches}
        <Comp matches={tablet} />
        <OtherComp matches={desktop} />
</MediaQuery>
```

### Expected

No type errors from Svelte.

### Actual

`Svelte: Type  boolean | QueryArray | ObjectType<any>  must have a  [Symbol.iterator]()  method that returns an iterator.`

---

Thanks by advance for your help!

**Comment by fedorovvvv** [comment]
Hi!
Thanks for the feedback, I've fixed everything in the [new version](https://github.com/fedorovvvv/svelte-media-queries/releases/tag/1.6.1)✨
