### ISSUE TITLE
Missing "." export in "svelte-media-queries" package

### ISSUE THREAD

**Issue by ksawery29** [fedorovvvv/svelte-media-queries#9]
Failed to resolve entry for package "svelte-media-queries". The package may have incorrect main/module/exports specified in its package.json: Missing "." export in "svelte-media-queries" package

**Comment by ryanspice** [comment]
@ksawery29 what was the solution?

**Comment by ksawery29** [comment]
well i just didn't use the library it founds out i can do the same thing with css. but if you want to use it you can create library similar to this in just one file, here's repl (note that this isn't mine): [url](https://svelte.dev/repl/26eb44932920421da01e2e21539494cd?version=3.55.0)

@ryanspice

**Comment by ryanspice** [comment]
> 

I managed to get it to work by doing;

  import MediaQuery from 'svelte-media-queries/components/MediaQuery.svelte'

**Comment by fedorovvvv** [comment]
Hi
Yes, unfortunately this is a problem svelte >= 3.54.0

Thanks for the fix
